import React, { useState, useRef } from 'react';
import { QRCodeCanvas, QRCodeSVG } from 'qrcode.react';
import { AdBanner } from '../components/AdBanner';
import { SEOHead, type FAQItem } from '../components/SEOHead';
import { ToolSeoContent } from '../components/ToolSeoContent';
import { FAQAccordion } from '../components/FAQAccordion';
import { 
  QrCode, 
  Download, 
  Palette, 
  Layers, 
  MessageSquare, 
  Wifi, 
  CreditCard, 
  FileText, 
  Check, 
  Copy,
  Sparkles,
  Store,
  Package,
  Share2
} from 'lucide-react';

type PresetType = 'chat' | 'wifi' | 'payment' | 'custom';

const qrGeneratorFaqs: FAQItem[] = [
  {
    question: 'How to generate a free WhatsApp QR code?',
    answer: 'Select the "WhatsApp Direct Chat" preset, enter your phone number with country code, add an optional pre-filled message, customize your brand colors, and click "Download PNG" or "SVG Vector".',
  },
  {
    question: 'Can I print these QR codes on business cards and store banners?',
    answer: 'Yes! WaKit generates high-resolution PNG images and vector SVG files suitable for professional printing on banners, flyers, product packaging, and business cards.',
  },
  {
    question: 'How does the WiFi Access QR code work?',
    answer: 'Scanning the WiFi QR code with any iPhone or Android camera automatically connects guests to your wireless network without typing the password manually.',
  },
  {
    question: 'Are there any scan limits or expiration dates for generated QR codes?',
    answer: 'No! All QR codes generated by WaKit are static vector codes. They never expire and have zero scan limits.',
  },
  {
    question: 'Can I add the official WhatsApp logo inside the center of the QR code?',
    answer: 'Yes! Toggle the "Embed WhatsApp Center Badge" checkbox to overlay an authentic center icon.',
  },
];

export const QRGeneratorPage: React.FC = () => {
  const [activePreset, setActivePreset] = useState<PresetType>('chat');
  
  const [fgColor, setFgColor] = useState('#075E54');
  const [bgColor, setBgColor] = useState('#FFFFFF');
  const [qrSize, setQrSize] = useState<number>(240);
  const [includeLogo, setIncludeLogo] = useState<boolean>(true);
  const [copied, setCopied] = useState(false);

  const [phone, setPhone] = useState('919876543210');
  const [messageText, setMessageText] = useState('Hello! Connecting via WaKit QR Code.');

  const [wifiSsid, setWifiSsid] = useState('Home_WiFi_5G');
  const [wifiPassword, setWifiPassword] = useState('secret123');
  const [wifiEncryption, setWifiEncryption] = useState<'WPA' | 'WEP' | 'nopass'>('WPA');

  const [upiId, setUpiId] = useState('merchant@upi');
  const [payAmount, setPayAmount] = useState('500');
  const [payNote, setPayNote] = useState('Services Payment');

  const [customContent, setCustomContent] = useState('https://wakit.app');

  const qrContainerRef = useRef<HTMLDivElement>(null);

  const finalQrPayload = React.useMemo(() => {
    switch (activePreset) {
      case 'chat': {
        const cleanP = phone.replace(/\D/g, '');
        const encText = encodeURIComponent(messageText);
        return `https://wa.me/${cleanP}${encText ? `?text=${encText}` : ''}`;
      }
      case 'wifi':
        return `WIFI:S:${wifiSsid};T:${wifiEncryption};P:${wifiPassword};;`;
      case 'payment':
        return `upi://pay?pa=${upiId}&pn=Recipient&am=${payAmount}&tn=${encodeURIComponent(payNote)}&cu=INR`;
      case 'custom':
        return customContent || 'https://wakit.app';
      default:
        return 'https://wakit.app';
    }
  }, [activePreset, phone, messageText, wifiSsid, wifiEncryption, wifiPassword, upiId, payAmount, payNote, customContent]);

  const handleDownloadPng = () => {
    const canvas = qrContainerRef.current?.querySelector('canvas');
    if (!canvas) return;
    const url = canvas.toDataURL('image/png');
    const a = document.createElement('a');
    a.href = url;
    a.download = `wakit_qr_${activePreset}_${Date.now()}.png`;
    a.click();
  };

  const handleDownloadSvg = () => {
    const svg = qrContainerRef.current?.querySelector('svg');
    if (!svg) return;
    const svgData = new XMLSerializer().serializeToString(svg);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const svgUrl = URL.createObjectURL(svgBlob);
    const downloadLink = document.createElement('a');
    downloadLink.href = svgUrl;
    downloadLink.download = `wakit_qr_${activePreset}_${Date.now()}.svg`;
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);
    URL.revokeObjectURL(svgUrl);
  };

  const handleCopyPayload = () => {
    navigator.clipboard.writeText(finalQrPayload);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <SEOHead
        title="WhatsApp Link & QR Code Generator – Free Scan-to-Chat QR | WhatsSwift"
        description="Generate WhatsApp chat links, Wi-Fi and payment QR codes free. Custom colors, PNG and SVG export. Private, in-browser, never expires."
        canonicalPath="/whatsapp-qr-code-generator"
        keywords="whatsapp link and qr code generator, whatsapp qr code generator free, scan to chat qr, wa.me qr builder"
        faqs={qrGeneratorFaqs}
        howToName="How to generate a WhatsApp QR code"
        howToSteps={[
          { name: 'Pick a preset', text: 'Choose WhatsApp direct chat, Wi-Fi access, payment prompt, or custom text/URL — each builds the correct QR payload format.' },
          { name: 'Fill in content and style', text: 'Enter the number or content, set brand colors, and toggle the WhatsApp center badge for a branded code.' },
          { name: 'Download and print', text: 'Export high-resolution PNG for sharing or vector SVG for business cards, banners, and packaging.' },
        ]}
      />

      {/* Title Header */}
      <div className="text-center space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-xs font-semibold border border-emerald-500/20">
          <QrCode className="w-3.5 h-3.5" />
          <span>High-Res Vector SVG & Canvas PNG Export</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
          WhatsApp QR Code Generator Free
        </h1>
        <p className="text-slate-600 dark:text-slate-400 text-sm max-w-xl mx-auto leading-relaxed">
          Create branded WhatsApp direct chat links, WiFi sharing codes, and payment prompts with customizable colors.
        </p>
      </div>

      {/* Presets Navigation Tabs */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        <button
          onClick={() => setActivePreset('chat')}
          className={`p-3 rounded-2xl border text-xs font-bold flex flex-col items-center gap-2 transition-all ${
            activePreset === 'chat'
              ? 'bg-emerald-500 text-white border-emerald-500 shadow-md shadow-emerald-500/20'
              : 'glass-pill text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800'
          }`}
        >
          <MessageSquare className="w-5 h-5" />
          <span>WhatsApp Direct Chat</span>
        </button>

        <button
          onClick={() => setActivePreset('wifi')}
          className={`p-3 rounded-2xl border text-xs font-bold flex flex-col items-center gap-2 transition-all ${
            activePreset === 'wifi'
              ? 'bg-emerald-500 text-white border-emerald-500 shadow-md shadow-emerald-500/20'
              : 'glass-pill text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800'
          }`}
        >
          <Wifi className="w-5 h-5" />
          <span>WiFi Access Share</span>
        </button>

        <button
          onClick={() => setActivePreset('payment')}
          className={`p-3 rounded-2xl border text-xs font-bold flex flex-col items-center gap-2 transition-all ${
            activePreset === 'payment'
              ? 'bg-emerald-500 text-white border-emerald-500 shadow-md shadow-emerald-500/20'
              : 'glass-pill text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800'
          }`}
        >
          <CreditCard className="w-5 h-5" />
          <span>Payment Prompt</span>
        </button>

        <button
          onClick={() => setActivePreset('custom')}
          className={`p-3 rounded-2xl border text-xs font-bold flex flex-col items-center gap-2 transition-all ${
            activePreset === 'custom'
              ? 'bg-emerald-500 text-white border-emerald-500 shadow-md shadow-emerald-500/20'
              : 'glass-pill text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800'
          }`}
        >
          <FileText className="w-5 h-5" />
          <span>Custom Text / URL</span>
        </button>
      </div>

      {/* Main Builder Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-7 glass-card p-6 sm:p-8 space-y-6">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Layers className="w-5 h-5 text-emerald-500" />
            <span>Preset Configuration</span>
          </h2>

          {activePreset === 'chat' && (
            <div className="space-y-4">
              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                  Phone Number (with Country Code, no +)
                </label>
                <input
                  type="text"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder="919876543210"
                  className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-mono text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                  Pre-filled Message Text
                </label>
                <textarea
                  rows={3}
                  value={messageText}
                  onChange={(e) => setMessageText(e.target.value)}
                  className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-xs sm:text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 resize-none"
                />
              </div>
            </div>
          )}

          {activePreset === 'wifi' && (
            <div className="space-y-4">
              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                  Network SSID (Name)
                </label>
                <input
                  type="text"
                  value={wifiSsid}
                  onChange={(e) => setWifiSsid(e.target.value)}
                  className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                  Password
                </label>
                <input
                  type="password"
                  value={wifiPassword}
                  onChange={(e) => setWifiPassword(e.target.value)}
                  className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 font-mono"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                  Encryption Type
                </label>
                <select
                  value={wifiEncryption}
                  onChange={(e) => setWifiEncryption(e.target.value as 'WPA' | 'WEP' | 'nopass')}
                  className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                >
                  <option value="WPA">WPA / WPA2 / WPA3 (Recommended)</option>
                  <option value="WEP">WEP</option>
                  <option value="nopass">None (Open Network)</option>
                </select>
              </div>
            </div>
          )}

          {activePreset === 'payment' && (
            <div className="space-y-4">
              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                  UPI ID / Merchant VPA
                </label>
                <input
                  type="text"
                  value={upiId}
                  onChange={(e) => setUpiId(e.target.value)}
                  placeholder="name@upi"
                  className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-mono text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                    Amount (₹)
                  </label>
                  <input
                    type="number"
                    value={payAmount}
                    onChange={(e) => setPayAmount(e.target.value)}
                    className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-mono text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                  />
                </div>
                <div className="space-y-1">
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                    Note / Remarks
                  </label>
                  <input
                    type="text"
                    value={payNote}
                    onChange={(e) => setPayNote(e.target.value)}
                    className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                  />
                </div>
              </div>
            </div>
          )}

          {activePreset === 'custom' && (
            <div className="space-y-1">
              <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                Custom Content or Web URL
              </label>
              <textarea
                rows={4}
                value={customContent}
                onChange={(e) => setCustomContent(e.target.value)}
                placeholder="https://..."
                className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-xs sm:text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 resize-none font-mono"
              />
            </div>
          )}

          <div className="pt-4 border-t border-slate-200 dark:border-slate-800 space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
              <Palette className="w-4 h-4 text-emerald-500" />
              <span>QR Style & Colors</span>
            </h3>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="block text-[11px] font-semibold text-slate-500 dark:text-slate-400">
                  Foreground Color
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={fgColor}
                    onChange={(e) => setFgColor(e.target.value)}
                    className="w-9 h-9 rounded-lg border-0 cursor-pointer"
                  />
                  <span className="font-mono text-xs text-slate-700 dark:text-slate-300">{fgColor}</span>
                </div>
              </div>

              <div className="space-y-1">
                <label className="block text-[11px] font-semibold text-slate-500 dark:text-slate-400">
                  Background Color
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={bgColor}
                    onChange={(e) => setBgColor(e.target.value)}
                    className="w-9 h-9 rounded-lg border-0 cursor-pointer"
                  />
                  <span className="font-mono text-xs text-slate-700 dark:text-slate-300">{bgColor}</span>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-between p-3 rounded-xl bg-slate-100/60 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
              <span className="text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-emerald-500" />
                <span>Embed WhatsApp Center Badge</span>
              </span>
              <input
                type="checkbox"
                checked={includeLogo}
                onChange={(e) => setIncludeLogo(e.target.checked)}
                className="w-4 h-4 accent-emerald-500 rounded cursor-pointer"
              />
            </div>

            <div className="space-y-1">
              <div className="flex justify-between text-[11px] font-semibold text-slate-500 dark:text-slate-400">
                <span>QR Display Size</span>
                <span className="font-mono">{qrSize}px</span>
              </div>
              <input
                type="range"
                min={180}
                max={320}
                step={20}
                value={qrSize}
                onChange={(e) => setQrSize(Number(e.target.value))}
                className="w-full accent-emerald-500 cursor-pointer"
              />
            </div>
          </div>
        </div>

        {/* Right Preview Card */}
        <div className="lg:col-span-5 glass-card p-6 sm:p-8 flex flex-col items-center justify-between space-y-6 text-center">
          <div className="space-y-1 w-full">
            <h3 className="font-bold text-base text-slate-900 dark:text-white">
              Live QR Preview
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              High-resolution canvas rendering with vector export options.
            </p>
          </div>

          <div
            ref={qrContainerRef}
            className="p-6 rounded-2xl bg-white shadow-xl border border-slate-200 dark:border-slate-800 flex items-center justify-center relative overflow-hidden"
            style={{ backgroundColor: bgColor }}
          >
            <QRCodeCanvas
              value={finalQrPayload}
              size={qrSize}
              fgColor={fgColor}
              bgColor={bgColor}
              level="H"
              includeMargin={true}
              imageSettings={
                includeLogo
                  ? {
                      src: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg',
                      x: undefined,
                      y: undefined,
                      height: 36,
                      width: 36,
                      excavate: true,
                    }
                  : undefined
              }
            />
            <div className="hidden">
              <QRCodeSVG
                value={finalQrPayload}
                size={500}
                fgColor={fgColor}
                bgColor={bgColor}
                level="H"
                includeMargin={true}
              />
            </div>
          </div>

          <div className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700/60 text-left space-y-1">
            <div className="flex items-center justify-between text-[11px]">
              <span className="font-semibold text-slate-500">QR Payload Target:</span>
              <button
                onClick={handleCopyPayload}
                className="text-emerald-500 hover:underline flex items-center gap-1 text-[10px] font-semibold"
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                <span>{copied ? 'Copied' : 'Copy Payload'}</span>
              </button>
            </div>
            <p className="font-mono text-[11px] text-slate-800 dark:text-slate-200 truncate">
              {finalQrPayload}
            </p>
          </div>

          <div className="w-full grid grid-cols-2 gap-3">
            <button
              type="button"
              onClick={handleDownloadPng}
              className="py-3 px-4 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white font-bold text-xs shadow-md shadow-emerald-500/20 transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>PNG (High-Res)</span>
            </button>

            <button
              type="button"
              onClick={handleDownloadSvg}
              className="py-3 px-4 rounded-xl bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs transition-colors flex items-center justify-center gap-2 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>SVG (Vector)</span>
            </button>
          </div>
        </div>
      </div>

      {/* Programmatic SEO Guides */}
      <section className="space-y-6 my-10">
        <h2 className="text-xl font-bold text-slate-900 dark:text-white text-center">
          Where to Use Custom WhatsApp QR Codes
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="glass-card p-6 space-y-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 flex items-center justify-center font-bold">
              <Store className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900 dark:text-white">Store Counter Banners</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
              Place a printed WhatsApp QR code at your store checkout for instant customer service orders and UPI payment prompts.
            </p>
          </div>

          <div className="glass-card p-6 space-y-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 flex items-center justify-center font-bold">
              <Package className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900 dark:text-white">Product Packaging Flyers</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
              Print vector SVG QR codes on product boxes and thank-you inserts so buyers can scan to request support or leave reviews.
            </p>
          </div>

          <div className="glass-card p-6 space-y-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 flex items-center justify-center font-bold">
              <Share2 className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-base text-slate-900 dark:text-white">WiFi & Guest Sharing</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
              Allow cafe guests and event attendees to connect to your guest WiFi instantly without typing complicated passwords.
            </p>
          </div>
        </div>
      </section>

      {/* SEO How-To + WASM explainer */}
      <ToolSeoContent
        toolName="WhatsApp Link & QR Code Generator"
        intro="Build scan-to-chat wa.me links plus Wi-Fi, payment, and custom QR codes — styled, exported, and printed in three steps."
        steps={[
          { name: 'Pick a Preset', text: 'Choose WhatsApp chat, Wi-Fi share, payment prompt, or custom text/URL to get the correct QR payload format instantly.' },
          { name: 'Customize & Brand', text: 'Enter your content, set foreground and background colors, and embed the WhatsApp center badge.' },
          { name: 'Download & Deploy', text: 'Export print-ready PNG or scalable SVG for store banners, packaging, business cards, and flyers.' },
        ]}
      />

      {/* Programmatic FAQ Section */}
      <FAQAccordion items={qrGeneratorFaqs} title="WhatsApp QR Code Generator FAQ" />

      <AdBanner type="leaderboard" />
    </div>
  );
};
